
#ifndef SMTP_INCLUDE_GUARD
#define SMTP_INCLUDE_GUARD

#define SMTP_MSG_TIMEOUT "TIMEOUT\r\n"
#define SMTP_MSG_OK "250 OK\r\n"
#include "client-fsm.h"
typedef enum  smtp_cmds_send_enum {
    SMTP_HELO_CMD = 0,
    SMTP_EHLO_CMD = 1,
    SMTP_MAIL_CMD = 2,
    SMTP_RCPT_CMD = 3,
    SMTP_DATA_CMD = 4,
    SMTP_RSET_CMD = 5,
    SMTP_QUIT_CMD = 6,
    SMTP_VRFY_CMD = 7,
    SMTP_NO_CMD = -1,
} smtp_cmds_send_t;

typedef enum  smtp_cmds_recv_enum {
    SMTP_SERVICE_READY, SMTP_SERVICE_CLOSING, SMTP_ANSWER_OK,SMTP_START_DATA_RESPONSE,
    SMTP_NOT_AVAIL_TRY_CONNECTION_CLOSE,SMTP_USER_MAIL_UNAVAIL, SMTP_ABORTED_BY_SERVER_ERROR, SMTP_SERVER_STORAGE_FULL, 
    SMTP_CANNOT_PROCESS_NOW,SMTP_CANNOT_PARSE_COMMAND,SMTP_CANNOT_PARSE_COMMAND_PARAM,SMTP_NOT_IMPLEMENTED,SMTP_BAD_SEQUENCE,
    SMTP_COMMAND_PARAM_NOT_IMPLEMENTED,SMTP_DUMMY_RESPONSE, SMTP_POLICY_REASON,SMTP_REQUESTED_COMMAND_FAILED,SMTP_RECIPIENT_NOT_LOCAL,
    SMTP_EXCEEDED_STORAGE_OF_RECIPIENT,SMTP_MAILBOX_NAME_INVALID,SMTP_MAILBOX_IS_DISABLED
} smtp_cmds_recv_t;



#define SMTP_CMD_CNT 8

#endif

