/*   -*- buffer-read-only: t -*- vi: set ro:
 *
 *  DO NOT EDIT THIS FILE   (server-fsm.c)
 *
 *  It has been AutoGen-ed
 *  From the definitions    server.def
 *  and the template file   fsm
 *
 *  Automated Finite State Machine
 *
 *  Copyright (C) 1992-2015 Bruce Korb - all rights reserved
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. Neither the name ``Bruce Korb'' nor the name of any other
 *    contributor may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * AutoFSM IS PROVIDED BY Bruce Korb ``AS IS'' AND ANY EXPRESS
 * OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL Bruce Korb OR ANY OTHER CONTRIBUTORS
 * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
 * BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 * OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 * ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
#define DEFINE_FSM
#include "server-fsm.h"
#include <stdio.h>

/*
 *  Do not make changes to this file, except between the START/END
 *  comments, or it will be removed the next time it is generated.
 */
/* START === USER HEADERS === DO NOT CHANGE THIS COMMENT */
#include <stdlib.h>

#include "../fsm_handlers.h"
/* END   === USER HEADERS === DO NOT CHANGE THIS COMMENT */

#ifndef NULL
#  define NULL 0
#endif

/**
 *  Enumeration of the valid transition types
 *  Some transition types may be common to several transitions.
 */
typedef enum {
    SERVER_FSM_TR_ACCEPTED,
    SERVER_FSM_TR_CLOSE,
    SERVER_FSM_TR_CMD_ERROR,
    SERVER_FSM_TR_DATA,
    SERVER_FSM_TR_EHLO,
    SERVER_FSM_TR_HELO,
    SERVER_FSM_TR_INVALID,
    SERVER_FSM_TR_LOST,
    SERVER_FSM_TR_MAIL,
    SERVER_FSM_TR_MAIL_RECEIVED,
    SERVER_FSM_TR_QUIT,
    SERVER_FSM_TR_RCPT,
    SERVER_FSM_TR_RSET,
    SERVER_FSM_TR_SYNTAX_ERROR,
    SERVER_FSM_TR_TIMEOUT,
    SERVER_FSM_TR_VRFY
} te_server_fsm_trans;
#define SERVER_FSM_TRANSITION_CT  16

/**
 *  State transition handling map.  Map the state enumeration and the event
 *  enumeration to the new state and the transition enumeration code (in that
 *  order).  It is indexed by first the current state and then the event code.
 */
typedef struct server_fsm_transition t_server_fsm_transition;
struct server_fsm_transition {
    te_server_fsm_state  next_state;
    te_server_fsm_trans  transition;
};
static const t_server_fsm_transition
server_fsm_trans_table[ SERVER_FSM_STATE_CT ][ SERVER_FSM_EVENT_CT ] = {

  /* STATE 0:  SERVER_FSM_ST_INIT */
  { { SERVER_FSM_ST_CREATED, SERVER_FSM_TR_ACCEPTED }, /* EVT:  ACCEPTED */
    { SERVER_FSM_ST_INVALID, SERVER_FSM_TR_INVALID }, /* EVT:  CMD_HELO */
    { SERVER_FSM_ST_INVALID, SERVER_FSM_TR_INVALID }, /* EVT:  CMD_EHLO */
    { SERVER_FSM_ST_INVALID, SERVER_FSM_TR_INVALID }, /* EVT:  CMD_MAIL */
    { SERVER_FSM_ST_INVALID, SERVER_FSM_TR_INVALID }, /* EVT:  CMD_RCPT */
    { SERVER_FSM_ST_INVALID, SERVER_FSM_TR_INVALID }, /* EVT:  CMD_DATA */
    { SERVER_FSM_ST_INVALID, SERVER_FSM_TR_INVALID }, /* EVT:  CMD_RSET */
    { SERVER_FSM_ST_INVALID, SERVER_FSM_TR_INVALID }, /* EVT:  CMD_VRFY */
    { SERVER_FSM_ST_INVALID, SERVER_FSM_TR_INVALID }, /* EVT:  CMD_QUIT */
    { SERVER_FSM_ST_INVALID, SERVER_FSM_TR_INVALID }, /* EVT:  MAIL_END */
    { SERVER_FSM_ST_DONE, SERVER_FSM_TR_LOST },     /* EVT:  CON_LOST */
    { SERVER_FSM_ST_INVALID, SERVER_FSM_TR_INVALID }, /* EVT:  TIMEOUT */
    { SERVER_FSM_ST_INVALID, SERVER_FSM_TR_INVALID }, /* EVT:  CON_CLOSE */
    { SERVER_FSM_ST_INVALID, SERVER_FSM_TR_INVALID }, /* EVT:  SYNTAX_ERROR */
    { SERVER_FSM_ST_INVALID, SERVER_FSM_TR_INVALID } /* EVT:  CMD_ERROR */
  },


  /* STATE 1:  SERVER_FSM_ST_CREATED */
  { { SERVER_FSM_ST_INVALID, SERVER_FSM_TR_INVALID }, /* EVT:  ACCEPTED */
    { SERVER_FSM_ST_HELLO, SERVER_FSM_TR_HELO },    /* EVT:  CMD_HELO */
    { SERVER_FSM_ST_HELLO, SERVER_FSM_TR_EHLO },    /* EVT:  CMD_EHLO */
    { SERVER_FSM_ST_INVALID, SERVER_FSM_TR_INVALID }, /* EVT:  CMD_MAIL */
    { SERVER_FSM_ST_INVALID, SERVER_FSM_TR_INVALID }, /* EVT:  CMD_RCPT */
    { SERVER_FSM_ST_INVALID, SERVER_FSM_TR_INVALID }, /* EVT:  CMD_DATA */
    { SERVER_FSM_ST_HELLO, SERVER_FSM_TR_RSET },    /* EVT:  CMD_RSET */
    { SERVER_FSM_ST_CREATED, SERVER_FSM_TR_VRFY },  /* EVT:  CMD_VRFY */
    { SERVER_FSM_ST_QUIT, SERVER_FSM_TR_QUIT },     /* EVT:  CMD_QUIT */
    { SERVER_FSM_ST_INVALID, SERVER_FSM_TR_INVALID }, /* EVT:  MAIL_END */
    { SERVER_FSM_ST_DONE, SERVER_FSM_TR_LOST },     /* EVT:  CON_LOST */
    { SERVER_FSM_ST_TIMEOUT, SERVER_FSM_TR_TIMEOUT }, /* EVT:  TIMEOUT */
    { SERVER_FSM_ST_INVALID, SERVER_FSM_TR_INVALID }, /* EVT:  CON_CLOSE */
    { SERVER_FSM_ST_CREATED, SERVER_FSM_TR_SYNTAX_ERROR }, /* EVT:  SYNTAX_ERROR */
    { SERVER_FSM_ST_CREATED, SERVER_FSM_TR_CMD_ERROR } /* EVT:  CMD_ERROR */
  },


  /* STATE 2:  SERVER_FSM_ST_HELLO */
  { { SERVER_FSM_ST_INVALID, SERVER_FSM_TR_INVALID }, /* EVT:  ACCEPTED */
    { SERVER_FSM_ST_HELLO, SERVER_FSM_TR_HELO },    /* EVT:  CMD_HELO */
    { SERVER_FSM_ST_HELLO, SERVER_FSM_TR_EHLO },    /* EVT:  CMD_EHLO */
    { SERVER_FSM_ST_MAIL_FROM, SERVER_FSM_TR_MAIL }, /* EVT:  CMD_MAIL */
    { SERVER_FSM_ST_INVALID, SERVER_FSM_TR_INVALID }, /* EVT:  CMD_RCPT */
    { SERVER_FSM_ST_INVALID, SERVER_FSM_TR_INVALID }, /* EVT:  CMD_DATA */
    { SERVER_FSM_ST_HELLO, SERVER_FSM_TR_RSET },    /* EVT:  CMD_RSET */
    { SERVER_FSM_ST_HELLO, SERVER_FSM_TR_VRFY },    /* EVT:  CMD_VRFY */
    { SERVER_FSM_ST_QUIT, SERVER_FSM_TR_QUIT },     /* EVT:  CMD_QUIT */
    { SERVER_FSM_ST_INVALID, SERVER_FSM_TR_INVALID }, /* EVT:  MAIL_END */
    { SERVER_FSM_ST_DONE, SERVER_FSM_TR_LOST },     /* EVT:  CON_LOST */
    { SERVER_FSM_ST_TIMEOUT, SERVER_FSM_TR_TIMEOUT }, /* EVT:  TIMEOUT */
    { SERVER_FSM_ST_INVALID, SERVER_FSM_TR_INVALID }, /* EVT:  CON_CLOSE */
    { SERVER_FSM_ST_HELLO, SERVER_FSM_TR_SYNTAX_ERROR }, /* EVT:  SYNTAX_ERROR */
    { SERVER_FSM_ST_HELLO, SERVER_FSM_TR_CMD_ERROR } /* EVT:  CMD_ERROR */
  },


  /* STATE 3:  SERVER_FSM_ST_MAIL_FROM */
  { { SERVER_FSM_ST_INVALID, SERVER_FSM_TR_INVALID }, /* EVT:  ACCEPTED */
    { SERVER_FSM_ST_HELLO, SERVER_FSM_TR_HELO },    /* EVT:  CMD_HELO */
    { SERVER_FSM_ST_HELLO, SERVER_FSM_TR_EHLO },    /* EVT:  CMD_EHLO */
    { SERVER_FSM_ST_INVALID, SERVER_FSM_TR_INVALID }, /* EVT:  CMD_MAIL */
    { SERVER_FSM_ST_RCPT_TO, SERVER_FSM_TR_RCPT },  /* EVT:  CMD_RCPT */
    { SERVER_FSM_ST_INVALID, SERVER_FSM_TR_INVALID }, /* EVT:  CMD_DATA */
    { SERVER_FSM_ST_HELLO, SERVER_FSM_TR_RSET },    /* EVT:  CMD_RSET */
    { SERVER_FSM_ST_MAIL_FROM, SERVER_FSM_TR_VRFY }, /* EVT:  CMD_VRFY */
    { SERVER_FSM_ST_QUIT, SERVER_FSM_TR_QUIT },     /* EVT:  CMD_QUIT */
    { SERVER_FSM_ST_INVALID, SERVER_FSM_TR_INVALID }, /* EVT:  MAIL_END */
    { SERVER_FSM_ST_DONE, SERVER_FSM_TR_LOST },     /* EVT:  CON_LOST */
    { SERVER_FSM_ST_TIMEOUT, SERVER_FSM_TR_TIMEOUT }, /* EVT:  TIMEOUT */
    { SERVER_FSM_ST_INVALID, SERVER_FSM_TR_INVALID }, /* EVT:  CON_CLOSE */
    { SERVER_FSM_ST_MAIL_FROM, SERVER_FSM_TR_SYNTAX_ERROR }, /* EVT:  SYNTAX_ERROR */
    { SERVER_FSM_ST_MAIL_FROM, SERVER_FSM_TR_CMD_ERROR } /* EVT:  CMD_ERROR */
  },


  /* STATE 4:  SERVER_FSM_ST_RCPT_TO */
  { { SERVER_FSM_ST_INVALID, SERVER_FSM_TR_INVALID }, /* EVT:  ACCEPTED */
    { SERVER_FSM_ST_HELLO, SERVER_FSM_TR_HELO },    /* EVT:  CMD_HELO */
    { SERVER_FSM_ST_HELLO, SERVER_FSM_TR_EHLO },    /* EVT:  CMD_EHLO */
    { SERVER_FSM_ST_INVALID, SERVER_FSM_TR_INVALID }, /* EVT:  CMD_MAIL */
    { SERVER_FSM_ST_RCPT_TO, SERVER_FSM_TR_RCPT },  /* EVT:  CMD_RCPT */
    { SERVER_FSM_ST_DATA, SERVER_FSM_TR_DATA },     /* EVT:  CMD_DATA */
    { SERVER_FSM_ST_HELLO, SERVER_FSM_TR_RSET },    /* EVT:  CMD_RSET */
    { SERVER_FSM_ST_RCPT_TO, SERVER_FSM_TR_VRFY },  /* EVT:  CMD_VRFY */
    { SERVER_FSM_ST_QUIT, SERVER_FSM_TR_QUIT },     /* EVT:  CMD_QUIT */
    { SERVER_FSM_ST_INVALID, SERVER_FSM_TR_INVALID }, /* EVT:  MAIL_END */
    { SERVER_FSM_ST_DONE, SERVER_FSM_TR_LOST },     /* EVT:  CON_LOST */
    { SERVER_FSM_ST_TIMEOUT, SERVER_FSM_TR_TIMEOUT }, /* EVT:  TIMEOUT */
    { SERVER_FSM_ST_INVALID, SERVER_FSM_TR_INVALID }, /* EVT:  CON_CLOSE */
    { SERVER_FSM_ST_RCPT_TO, SERVER_FSM_TR_SYNTAX_ERROR }, /* EVT:  SYNTAX_ERROR */
    { SERVER_FSM_ST_RCPT_TO, SERVER_FSM_TR_CMD_ERROR } /* EVT:  CMD_ERROR */
  },


  /* STATE 5:  SERVER_FSM_ST_DATA */
  { { SERVER_FSM_ST_INVALID, SERVER_FSM_TR_INVALID }, /* EVT:  ACCEPTED */
    { SERVER_FSM_ST_INVALID, SERVER_FSM_TR_INVALID }, /* EVT:  CMD_HELO */
    { SERVER_FSM_ST_INVALID, SERVER_FSM_TR_INVALID }, /* EVT:  CMD_EHLO */
    { SERVER_FSM_ST_INVALID, SERVER_FSM_TR_INVALID }, /* EVT:  CMD_MAIL */
    { SERVER_FSM_ST_INVALID, SERVER_FSM_TR_INVALID }, /* EVT:  CMD_RCPT */
    { SERVER_FSM_ST_INVALID, SERVER_FSM_TR_INVALID }, /* EVT:  CMD_DATA */
    { SERVER_FSM_ST_INVALID, SERVER_FSM_TR_INVALID }, /* EVT:  CMD_RSET */
    { SERVER_FSM_ST_INVALID, SERVER_FSM_TR_INVALID }, /* EVT:  CMD_VRFY */
    { SERVER_FSM_ST_INVALID, SERVER_FSM_TR_INVALID }, /* EVT:  CMD_QUIT */
    { SERVER_FSM_ST_HELLO, SERVER_FSM_TR_MAIL_RECEIVED }, /* EVT:  MAIL_END */
    { SERVER_FSM_ST_DONE, SERVER_FSM_TR_LOST },     /* EVT:  CON_LOST */
    { SERVER_FSM_ST_TIMEOUT, SERVER_FSM_TR_TIMEOUT }, /* EVT:  TIMEOUT */
    { SERVER_FSM_ST_INVALID, SERVER_FSM_TR_INVALID }, /* EVT:  CON_CLOSE */
    { SERVER_FSM_ST_INVALID, SERVER_FSM_TR_INVALID }, /* EVT:  SYNTAX_ERROR */
    { SERVER_FSM_ST_INVALID, SERVER_FSM_TR_INVALID } /* EVT:  CMD_ERROR */
  },


  /* STATE 6:  SERVER_FSM_ST_QUIT */
  { { SERVER_FSM_ST_INVALID, SERVER_FSM_TR_INVALID }, /* EVT:  ACCEPTED */
    { SERVER_FSM_ST_INVALID, SERVER_FSM_TR_INVALID }, /* EVT:  CMD_HELO */
    { SERVER_FSM_ST_INVALID, SERVER_FSM_TR_INVALID }, /* EVT:  CMD_EHLO */
    { SERVER_FSM_ST_INVALID, SERVER_FSM_TR_INVALID }, /* EVT:  CMD_MAIL */
    { SERVER_FSM_ST_INVALID, SERVER_FSM_TR_INVALID }, /* EVT:  CMD_RCPT */
    { SERVER_FSM_ST_INVALID, SERVER_FSM_TR_INVALID }, /* EVT:  CMD_DATA */
    { SERVER_FSM_ST_INVALID, SERVER_FSM_TR_INVALID }, /* EVT:  CMD_RSET */
    { SERVER_FSM_ST_INVALID, SERVER_FSM_TR_INVALID }, /* EVT:  CMD_VRFY */
    { SERVER_FSM_ST_INVALID, SERVER_FSM_TR_INVALID }, /* EVT:  CMD_QUIT */
    { SERVER_FSM_ST_INVALID, SERVER_FSM_TR_INVALID }, /* EVT:  MAIL_END */
    { SERVER_FSM_ST_DONE, SERVER_FSM_TR_LOST },     /* EVT:  CON_LOST */
    { SERVER_FSM_ST_INVALID, SERVER_FSM_TR_INVALID }, /* EVT:  TIMEOUT */
    { SERVER_FSM_ST_DONE, SERVER_FSM_TR_CLOSE },    /* EVT:  CON_CLOSE */
    { SERVER_FSM_ST_INVALID, SERVER_FSM_TR_INVALID }, /* EVT:  SYNTAX_ERROR */
    { SERVER_FSM_ST_INVALID, SERVER_FSM_TR_INVALID } /* EVT:  CMD_ERROR */
  },


  /* STATE 7:  SERVER_FSM_ST_TIMEOUT */
  { { SERVER_FSM_ST_INVALID, SERVER_FSM_TR_INVALID }, /* EVT:  ACCEPTED */
    { SERVER_FSM_ST_INVALID, SERVER_FSM_TR_INVALID }, /* EVT:  CMD_HELO */
    { SERVER_FSM_ST_INVALID, SERVER_FSM_TR_INVALID }, /* EVT:  CMD_EHLO */
    { SERVER_FSM_ST_INVALID, SERVER_FSM_TR_INVALID }, /* EVT:  CMD_MAIL */
    { SERVER_FSM_ST_INVALID, SERVER_FSM_TR_INVALID }, /* EVT:  CMD_RCPT */
    { SERVER_FSM_ST_INVALID, SERVER_FSM_TR_INVALID }, /* EVT:  CMD_DATA */
    { SERVER_FSM_ST_INVALID, SERVER_FSM_TR_INVALID }, /* EVT:  CMD_RSET */
    { SERVER_FSM_ST_INVALID, SERVER_FSM_TR_INVALID }, /* EVT:  CMD_VRFY */
    { SERVER_FSM_ST_INVALID, SERVER_FSM_TR_INVALID }, /* EVT:  CMD_QUIT */
    { SERVER_FSM_ST_INVALID, SERVER_FSM_TR_INVALID }, /* EVT:  MAIL_END */
    { SERVER_FSM_ST_DONE, SERVER_FSM_TR_LOST },     /* EVT:  CON_LOST */
    { SERVER_FSM_ST_INVALID, SERVER_FSM_TR_INVALID }, /* EVT:  TIMEOUT */
    { SERVER_FSM_ST_DONE, SERVER_FSM_TR_CLOSE },    /* EVT:  CON_CLOSE */
    { SERVER_FSM_ST_INVALID, SERVER_FSM_TR_INVALID }, /* EVT:  SYNTAX_ERROR */
    { SERVER_FSM_ST_INVALID, SERVER_FSM_TR_INVALID } /* EVT:  CMD_ERROR */
  }
};


#define Server_FsmFsmErr_off     19
#define Server_FsmEvInvalid_off  75
#define Server_FsmStInit_off     83


static char const zServer_FsmStrings[270] =
/*     0 */ "** OUT-OF-RANGE **\0"
/*    19 */ "FSM Error:  in state %d (%s), event %d (%s) is invalid\n\0"
/*    75 */ "invalid\0"
/*    83 */ "init\0"
/*    88 */ "created\0"
/*    96 */ "hello\0"
/*   102 */ "mail_from\0"
/*   112 */ "rcpt_to\0"
/*   120 */ "data\0"
/*   125 */ "quit\0"
/*   130 */ "timeout\0"
/*   138 */ "accepted\0"
/*   147 */ "cmd_helo\0"
/*   156 */ "cmd_ehlo\0"
/*   165 */ "cmd_mail\0"
/*   174 */ "cmd_rcpt\0"
/*   183 */ "cmd_data\0"
/*   192 */ "cmd_rset\0"
/*   201 */ "cmd_vrfy\0"
/*   210 */ "cmd_quit\0"
/*   219 */ "mail_end\0"
/*   228 */ "con_lost\0"
/*   237 */ "con_close\0"
/*   247 */ "syntax_error\0"
/*   260 */ "cmd_error";

static const size_t aszServer_FsmStates[8] = {
    83,  88,  96,  102, 112, 120, 125, 130 };

static const size_t aszServer_FsmEvents[16] = {
    138, 147, 156, 165, 174, 183, 192, 201, 210, 219, 228, 130, 237, 247, 260,
    75 };


#define SERVER_FSM_EVT_NAME(t)   ( (((unsigned)(t)) >= 16) \
    ? zServer_FsmStrings : zServer_FsmStrings + aszServer_FsmEvents[t])

#define SERVER_FSM_STATE_NAME(s) ( (((unsigned)(s)) >= 8) \
    ? zServer_FsmStrings : zServer_FsmStrings + aszServer_FsmStates[s])

#ifndef EXIT_FAILURE
# define EXIT_FAILURE 1
#endif

static int server_fsm_invalid_transition( te_server_fsm_state st, te_server_fsm_event evt );

/* * * * * * * * * THE CODE STARTS HERE * * * * * * * */
/**
 *  Print out an invalid transition message and return EXIT_FAILURE
 */
static int
server_fsm_invalid_transition( te_server_fsm_state st, te_server_fsm_event evt )
{
    /* START == INVALID TRANS MSG == DO NOT CHANGE THIS COMMENT */
    char const * fmt = zServer_FsmStrings + Server_FsmFsmErr_off;
    fprintf( stderr, fmt, st, SERVER_FSM_STATE_NAME(st), evt, SERVER_FSM_EVT_NAME(evt));
    /* END   == INVALID TRANS MSG == DO NOT CHANGE THIS COMMENT */

    return EXIT_FAILURE;
}

/**
 *  Step the FSM.  Returns the resulting state.  If the current state is
 *  SERVER_FSM_ST_DONE or SERVER_FSM_ST_INVALID, it resets to
 *  SERVER_FSM_ST_INIT and returns SERVER_FSM_ST_INIT.
 */
te_server_fsm_state
server_fsm_step(
    te_server_fsm_state server_fsm_state,
    te_server_fsm_event trans_evt,
    void *server,
    void *data_str )
{
    te_server_fsm_state nxtSt;
    te_server_fsm_trans trans;

    if ((unsigned)server_fsm_state >= SERVER_FSM_ST_INVALID) {
        return SERVER_FSM_ST_INIT;
    }

#ifndef __COVERITY__
    if (trans_evt >= SERVER_FSM_EV_INVALID) {
        nxtSt = SERVER_FSM_ST_INVALID;
        trans = SERVER_FSM_TR_INVALID;
    } else
#endif /* __COVERITY__ */
    {
        const t_server_fsm_transition * ttbl =
            server_fsm_trans_table[ server_fsm_state ] + trans_evt;
        nxtSt = ttbl->next_state;
        trans = ttbl->transition;
    }


    switch (trans) {
    case SERVER_FSM_TR_ACCEPTED:
        /* START == ACCEPTED == DO NOT CHANGE THIS COMMENT */
        nxtSt = fsm_handle_accepted(server, nxtSt);
        /* END   == ACCEPTED == DO NOT CHANGE THIS COMMENT */
        break;


    case SERVER_FSM_TR_CLOSE:
        /* START == CLOSE == DO NOT CHANGE THIS COMMENT */
        nxtSt = fsm_handle_close(server, nxtSt);
        /* END   == CLOSE == DO NOT CHANGE THIS COMMENT */
        break;


    case SERVER_FSM_TR_CMD_ERROR:
        /* START == CMD_ERROR == DO NOT CHANGE THIS COMMENT */
        nxtSt = fsm_handle_cmd_error(server, nxtSt);
        /* END   == CMD_ERROR == DO NOT CHANGE THIS COMMENT */
        break;


    case SERVER_FSM_TR_DATA:
        /* START == DATA == DO NOT CHANGE THIS COMMENT */
        nxtSt = fsm_handle_data(server, nxtSt);
        /* END   == DATA == DO NOT CHANGE THIS COMMENT */
        break;


    case SERVER_FSM_TR_EHLO:
        /* START == EHLO == DO NOT CHANGE THIS COMMENT */
        nxtSt = fsm_handle_ehlo(server, data_str, nxtSt);
        /* END   == EHLO == DO NOT CHANGE THIS COMMENT */
        break;


    case SERVER_FSM_TR_HELO:
        /* START == HELO == DO NOT CHANGE THIS COMMENT */
        nxtSt = fsm_handle_helo(server, data_str, nxtSt);
        /* END   == HELO == DO NOT CHANGE THIS COMMENT */
        break;


    case SERVER_FSM_TR_INVALID:
        /* START == INVALID == DO NOT CHANGE THIS COMMENT */
        nxtSt = fsm_handle_invalid(server, nxtSt);
        /* END   == INVALID == DO NOT CHANGE THIS COMMENT */
        break;


    case SERVER_FSM_TR_LOST:
        /* START == LOST == DO NOT CHANGE THIS COMMENT */
        nxtSt = fsm_handle_lost(server, nxtSt);
        /* END   == LOST == DO NOT CHANGE THIS COMMENT */
        break;


    case SERVER_FSM_TR_MAIL:
        /* START == MAIL == DO NOT CHANGE THIS COMMENT */
        nxtSt = fsm_handle_mail(server, data_str, nxtSt);
        /* END   == MAIL == DO NOT CHANGE THIS COMMENT */
        break;


    case SERVER_FSM_TR_MAIL_RECEIVED:
        /* START == MAIL_RECEIVED == DO NOT CHANGE THIS COMMENT */
        nxtSt = fsm_handle_mail_end(server, nxtSt);
        /* END   == MAIL_RECEIVED == DO NOT CHANGE THIS COMMENT */
        break;


    case SERVER_FSM_TR_QUIT:
        /* START == QUIT == DO NOT CHANGE THIS COMMENT */
        nxtSt = fsm_handle_quit(server, nxtSt);
        /* END   == QUIT == DO NOT CHANGE THIS COMMENT */
        break;


    case SERVER_FSM_TR_RCPT:
        /* START == RCPT == DO NOT CHANGE THIS COMMENT */
        nxtSt = fsm_handle_rcpt(server, data_str, nxtSt);
        /* END   == RCPT == DO NOT CHANGE THIS COMMENT */
        break;


    case SERVER_FSM_TR_RSET:
        /* START == RSET == DO NOT CHANGE THIS COMMENT */
        nxtSt = fsm_handle_rset(server, nxtSt);
        /* END   == RSET == DO NOT CHANGE THIS COMMENT */
        break;


    case SERVER_FSM_TR_SYNTAX_ERROR:
        /* START == SYNTAX_ERROR == DO NOT CHANGE THIS COMMENT */
        nxtSt = fsm_handle_syntax_error(server, nxtSt);
        /* END   == SYNTAX_ERROR == DO NOT CHANGE THIS COMMENT */
        break;


    case SERVER_FSM_TR_TIMEOUT:
        /* START == TIMEOUT == DO NOT CHANGE THIS COMMENT */
        nxtSt = fsm_handle_timeout(server, nxtSt);
        /* END   == TIMEOUT == DO NOT CHANGE THIS COMMENT */
        break;


    case SERVER_FSM_TR_VRFY:
        /* START == VRFY == DO NOT CHANGE THIS COMMENT */
        nxtSt = fsm_handle_vrfy(server, nxtSt);
        /* END   == VRFY == DO NOT CHANGE THIS COMMENT */
        break;


    default:
        /* START == BROKEN MACHINE == DO NOT CHANGE THIS COMMENT */
        exit(server_fsm_invalid_transition(server_fsm_state, trans_evt));
        /* END   == BROKEN MACHINE == DO NOT CHANGE THIS COMMENT */
    }


    /* START == FINISH STEP == DO NOT CHANGE THIS COMMENT */
    /* END   == FINISH STEP == DO NOT CHANGE THIS COMMENT */

    return nxtSt;
}
/*
 * Local Variables:
 * mode: C
 * c-file-style: "stroustrup"
 * indent-tabs-mode: nil
 * End:
 * end of server-fsm.c */
